# From https://github.com/Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi

class COMMAND:
    MOVE_STOP = "CMD_MOVE_STOP"
    MOVE_FORWARD = "CMD_MOVE_FORWARD"
    MOVE_BACKWARD = "CMD_MOVE_BACKWARD"
    MOVE_LEFT = "CMD_MOVE_LEFT"
    MOVE_RIGHT = "CMD_MOVE_RIGHT"
    TURN_LEFT = "CMD_TURN_LEFT"
    TURN_RIGHT = "CMD_TURN_RIGHT"
    BUZZER = "CMD_BUZZER"
    LED_MOD = "CMD_LED_MOD"
    LED = "CMD_LED"
    BALANCE = "CMD_BALANCE"
    SONIC = "CMD_SONIC"
    HEIGHT = "CMD_HEIGHT"
    HORIZON = "CMD_HORIZON"
    HEAD = "CMD_HEAD"
    CALIBRATION = "CMD_CALIBRATION"
    POWER = "CMD_POWER"
    ATTITUDE = "CMD_ATTITUDE"
    RELAX = "CMD_RELAX"
    def __init__(self):
        pass
